const languageSelect = document.createElement('select');
languageSelect.id = 'language-select';
languageSelect.innerHTML = `
    <option value="zh">中文</option>
    <option value="en">English</option>
    <option value="ar">العربية</option>
`;
const languageToggle = document.createElement('div');
languageToggle.className = 'language-toggle';
languageToggle.appendChild(languageSelect);
document.querySelector('header').appendChild(languageToggle);

const translations = {
    zh: {
        "hero.title": "Launch Your Business in Ethiopia with Unify Consultancy<br>与Unify Consultancy一起在埃塞俄比亚开启您的商业之旅",
        "hero.subtitle": "We provide fast, cost-effective solutions for Chinese investors, from visas and licenses to legal and financial consultancy.<br>我们为中国投资者提供快速、成本效益高的解决方案，涵盖签证、许可证、法律和财务咨询。",
        "hero.cta": "Book a Consultation | 预约咨询",
        "services.title": "Our Services | 我们的服务",
        "services.economic.title": "Economic Development Consultancy<br>经济发展咨询",
        "services.economic.description": "Expert strategies for market entry in Ethiopia.<br>为埃塞俄比亚市场进入提供专家策略。",
        "services.economic.overview": "Unify Consultancy offers expert strategies for market entry in Ethiopia, helping Chinese nationals identify growth opportunities.<br>咨询统为中国公民提供市场进入的专家策略，帮助他们在埃塞俄比亚识别增长机会。",
        "services.economic.process": "1. Consultation | 咨询 2. Market Analysis | 市场分析 3. Strategy Implementation | 策略实施",
        "services.economic.case_study": "A Chinese firm identified growth opportunities with our guidance.<br>一家中国公司在我们指导下发现了增长机会。",
        "services.business.title": "Business and Investment Consultancy<br>商业与投资咨询",
        "services.business.description": "Support for business setup in any industry.<br>支持任何行业的商业设立。",
        "services.business.overview": "We guide you through business setup in Ethiopia across any industry.<br>我们指导您在埃塞俄比亚任何行业设立业务。",
        "services.business.process": "1. Planning | 规划 2. Execution | 执行 3. Growth | 增长",
        "services.business.case_study": "A client successfully launched a manufacturing unit in Addis Ababa.<br>一位客户在亚的斯亚贝巴成功启动了一家制造单位。",
        "services.visa.title": "Visa Processing<br>签证处理",
        "services.visa.description": "Secure investor visas quickly with our process.<br>通过我们流程快速获得投资签证。",
        "services.visa.overview": "Fast-tracked visa processing for Chinese investors.<br>为中国投资者快速处理签证。",
        "services.visa.process": "1. Document Collection | 文件收集 2. Application Submission | 申请提交 3. Approval | 批准",
        "services.visa.case_study": "Processed 50+ visas in one month for a corporate group.<br>为一家企业集团在一个月内处理了50多份签证。",
        "services.work.title": "Work Permits<br>工作许可",
        "services.work.description": "Streamlined permits for Chinese employees.<br>为中国员工提供简化的许可。",
        "services.work.overview": "Hassle-free work permits for your team in Ethiopia.<br>为您的团队在埃塞俄比亚提供无忧工作许可。",
        "services.work.process": "1. Application | 申请 2. Verification | 验证 3. Issuance | 签发",
        "services.work.case_study": "Secured permits for 20 employees in two weeks.<br>在两周内为20名员工获得了许可。",
        "services.residence.title": "Residence Permits<br>居留许可",
        "services.residence.description": "Support for long-term stays in Ethiopia.<br>支持在埃塞俄比亚的长期居留。",
        "services.residence.overview": "Long-term residence permits for investors and families.<br>为投资者和家庭提供长期居留许可。",
        "services.residence.process": "1. Documentation | 文件 2. Submission | 提交 3. Approval | 批准",
        "services.residence.case_study": "Helped a family secure residence permits in one month.<br>帮助一个家庭在一个月内获得居留许可。",
        "services.license.title": "Business License Processing<br>商业许可处理",
        "services.license.description": "Navigate licensing requirements with ease.<br>轻松应对许可要求。",
        "services.license.overview": "Effortless business license processing in Ethiopia.<br>在埃塞俄比亚轻松处理商业许可。",
        "services.license.process": "1. Consultation | 咨询 2. Application | 申请 3. Approval | 批准",
        "services.license.case_study": "Secured a license for a retail business in three weeks.<br>在三周内为一家零售企业获得了许可。",
        "services.legal.title": "Legal Consultancy<br>法律咨询",
        "services.legal.description": "Expert advice on business compliance.<br>关于商业合规的专家建议。",
        "services.legal.overview": "Legal support for business compliance in Ethiopia.<br>为埃塞俄比亚的商业合规提供法律支持。",
        "services.legal.process": "1. Assessment | 评估 2. Advisory | 咨询 3. Compliance | 合规",
        "services.legal.case_study": "Resolved a compliance issue for a Chinese firm.<br>为一家中国公司解决了合规问题。",
        "services.financial.title": "Financial Consultancy<br>财务咨询",
        "services.financial.description": "Optimize your investments with expert planning.<br>通过专家规划优化您的投资。",
        "services.financial.overview": "Financial planning and investment optimization for investors.<br>为投资者提供财务规划和投资优化。",
        "services.financial.process": "1. Analysis | 分析 2. Planning | 规划 3. Execution | 执行",
        "services.financial.case_study": "Improved ROI for a client’s investment portfolio.<br>为客户的投资组合提高了回报率。",
        "services.overview": "Overview | 概述",
        "services.process": "Process | 流程",
        "services.case_study": "Case Study | 案例研究",
        "services.cta": "Start Now | 开始",
        "services.link": "Learn More | 了解更多",
        "why.title": "Why Unify Consultancy | 为什么选择Unify Consultancy",
        "why.description": "With over 500 visas processed and 300 licenses secured, we’re trusted by Chinese investors.<br>我们已处理超过500个签证和300个许可，深受中国投资者信赖。",
        "why.testimonial": "“Unify Consultancy helped me secure a business license in just weeks!” – Sample Client<br>“Unify Consultancy在几周内帮我获得了商业许可！” – 示例客户",
        "why.hero.title": "Why Unify Consultancy is Your Best Choice for Ethiopia<br>为何Unify Consultancy是您在埃塞俄比亚的最佳选择",
        "why.hero.subtitle": "Fast, cost-effective, and expert solutions for Chinese investors.<br>为中国投资者提供快速、成本效益高且专业的解决方案。",
        "why.strengths.speed.title": "Speed<br>速度",
        "why.strengths.speed.description": "We deliver visas and licenses in weeks, not months.<br>我们几周内交付签证和许可，而非数月。",
        "why.strengths.cost.title": "Cost-Effectiveness<br>成本效益",
        "why.strengths.cost.description": "Transparent pricing for premium services.<br>透明定价的优质服务。",
        "why.strengths.expertise.title": "Expertise<br>专业知识",
        "why.strengths.expertise.description": "Specialists in visa, legal, and financial consultancy.<br>签证、法律和财务咨询专家。",
        "why.strengths.network.title": "Wide Network<br>广泛网络",
        "why.strengths.network.description": "Connections with Ethiopian immigration and government.<br>与埃塞俄比亚移民和政府的联系。",
        "why.testimonial1": "“Unify Consultancy’s speed made starting my business effortless!” – Sample Client<br>“Unify Consultancy的速度让创业变得轻松！” – 示例客户",
        "why.testimonial2": "“Their network saved us weeks of delays.” – Sample Client<br>“他们的网络为我们节省了数周延误。” – 示例客户",
        "why.cta.button": "Start Your Journey with Us | 与我们开始您的旅程",
        "cta.title": "Request a Free Consultation | 请求免费咨询",
        "cta.button": "Get Started | 开始",
        "about.hero.title": "Your Trusted Partner for Business Success in Ethiopia<br>您在埃塞俄比亚商业成功的可靠伙伴",
        "about.hero.subtitle": "Unify Consultancy delivers fast, expert solutions for Chinese investors.<br>Unify Consultancy为中国投资者提供快速、专业的解决方案。",
        "about.hero.cta": "Contact Our Team | 联系我们的团队",
        "about.mission.title": "Our Mission | 我们的使命",
        "about.mission.description": "At Unify Consultancy, our mission is to empower Chinese nationals to succeed in Ethiopia’s vibrant business environment.<br>在Unify Consultancy，我们的使命是助力中国公民在埃塞俄比亚充满活力的商业环境中取得成功。",
        "about.expertise.title": "Our Expertise | 我们的专长",
        "about.expertise.description": "With over 500 visas processed and 300 licenses secured, we’re a trusted leader for Chinese investors in Ethiopia.<br>我们已处理超过500个签证和300个许可，是中国投资者在埃塞俄比亚的信赖领导者。",
        "about.team.title": "Our Team | 我们的团队",
        "about.team.description": "Our team of experts in visa processing, legal consultancy, and financial planning is passionate about helping Chinese investors thrive. [Bios to be added later.]<br>我们的签证处理、法律咨询和财务规划专家团队热衷于帮助中国投资者蓬勃发展。[简介稍后添加。]",
        "about.certifications.title": "Certifications | 认证",
        "about.certifications.description": "Unify Consultancy maintains affiliations with leading industry organizations, ensuring quality in all services. [Details to be added later.]<br>Unify Consultancy与领先的行业组织保持联系，确保所有服务的质量。[详情稍后添加。]",
        "resources.hero.title": "Resources to Start Your Business in Ethiopia<br>在埃塞俄比亚创业的资源",
        "resources.hero.subtitle": "Explore expert guides and insights for Chinese investors.<br>为中国投资者探索专业指南和见解。",
        "resources.tips.title": "Top 5 Tips for Chinese Nationals to Secure an Investor Visa<br>中国公民获得投资签证的五大技巧",
        "resources.tips.description": "Learn the key steps to a successful visa application.<br>了解成功签证申请的关键步骤。",
        "resources.tips.link": "Read More | 阅读更多",
        "resources.checklist.title": "Ethiopia Investor Visa Checklist<br>埃塞俄比亚投资签证清单",
        "resources.checklist.description": "Download our free checklist to prepare your application.<br>下载我们的免费清单以准备您的申请。",
        "resources.checklist.link": "Download | 下载",
        "resources.newsletter.title": "Stay Updated | 保持更新",
        "resources.newsletter.description": "Stay updated on Ethiopia’s immigration policies and business opportunities.<br>了解埃塞俄比亚的移民政策和商业机会。",
        "resources.newsletter.placeholder": "Your Email | 您的邮箱",
        "resources.newsletter.button": "Subscribe | 订阅",
        "contact.hero.title": "Get in Touch with Unify Consultancy<br>与Unify Consultancy联系",
        "contact.hero.subtitle": "Start your business journey in Ethiopia today.<br>今天开始您在埃塞俄比亚的商业之旅。",
        "contact.form.title": "Contact Us | 联系我们",
        "contact.form.subtitle": "Have questions about visas, licenses, or starting a business in Ethiopia? Fill out the form below.<br>关于签证、许可或在埃塞俄比亚创业有疑问？请填写下面的表格。",
        "contact.form.name": "Name | 姓名",
        "contact.form.email": "Email | 邮箱",
        "contact.form.phone": "Phone | 电话",
        "contact.form.service": "Service Type | 服务类型",
        "contact.form.service.visa": "Visa Processing | 签证处理",
        "contact.form.service.license": "Business License Processing | 商业许可处理",
        "contact.form.service.legal": "Legal Consultancy | 法律咨询",
        "contact.form.service.financial": "Financial Consultancy | 财务咨询",
        "contact.form.message": "Message | 消息",
        "contact.form.submit": "Submit | 提交",
        "contact.booking.title": "Book a Free Consultation | 预约免费咨询",
        "contact.booking.subtitle": "Schedule a free consultation with our experts.<br>与我们的专家安排免费咨询。",
        "contact.details.title": "Contact Information | 联系信息",
        "contact.details.info": "Phone: [Your Phone Number] | 电话： [您的电话号码]<br>Email: [Your Email] | 邮箱： [您的邮箱]<br>Address: [Your Address, e.g., Addis Ababa, Ethiopia] | 地址： [您的地址，例如亚的斯亚贝巴，埃塞俄比亚]",
        "portal.hero.title": "Client Portal | 客户门户",
        "portal.hero.subtitle": "Track the status of your applications with Unify Consultancy.<br>与Unify Consultancy跟踪您的申请状态。",
        "portal.login.title": "Login to Your Portal | 登录您的门户",
        "portal.login.subtitle": "Client Portal is under development. Please login with your credentials.<br>客户门户正在开发中。请使用您的凭据登录。",
        "portal.login.username": "Username | 用户名",
        "portal.login.password": "Password | 密码",
        "portal.login.button": "Login | 登录",
        "portal.login.support": "Or <a href='contact.html'>contact us</a> for support.<br>或<a href='contact.html'>联系我们</a>获取支持。",
        "nav.home": "Home | 首页",
        "nav.about": "About Us | 关于我们",
        "nav.services": "Services | 服务",
        "nav.why": "Why Choose Us | 选择我们",
        "nav.resources": "Resources | 资源",
        "nav.contact": "Contact Us | 联系我们",
        "nav.portal": "Client Portal | 客户门户",
        "footer.copyright": "© 2025 Unify Consultancy. All rights reserved.<br>© 2025 咨询统。版权所有。",
        "footer.contact": "Contact Us | 联系我们"
    },
    en: {
        "hero.title": "Launch Your Business in Ethiopia with Unify Consultancy",
        "hero.subtitle": "We provide fast, cost-effective solutions for Chinese investors, from visas and licenses to legal and financial consultancy.",
        "hero.cta": "Book a Consultation",
        "services.title": "Our Services",
        "services.economic.title": "Economic Development Consultancy",
        "services.economic.description": "Expert strategies for market entry in Ethiopia.",
        "services.economic.overview": "Unify Consultancy offers expert strategies for market entry in Ethiopia, helping Chinese nationals identify growth opportunities.",
        "services.economic.process": "1. Consultation 2. Market Analysis 3. Strategy Implementation",
        "services.economic.case_study": "A Chinese firm identified growth opportunities with our guidance.",
        "services.business.title": "Business and Investment Consultancy",
        "services.business.description": "Support for business setup in any industry.",
        "services.business.overview": "We guide you through business setup in Ethiopia across any industry.",
        "services.business.process": "1. Planning 2. Execution 3. Growth",
        "services.business.case_study": "A client successfully launched a manufacturing unit in Addis Ababa.",
        "services.visa.title": "Visa Processing",
        "services.visa.description": "Secure investor visas quickly with our process.",
        "services.visa.overview": "Fast-tracked visa processing for Chinese investors.",
        "services.visa.process": "1. Document Collection 2. Application Submission 3. Approval",
        "services.visa.case_study": "Processed 50+ visas in one month for a corporate group.",
        "services.work.title": "Work Permits",
        "services.work.description": "Streamlined permits for Chinese employees.",
        "services.work.overview": "Hassle-free work permits for your team in Ethiopia.",
        "services.work.process": "1. Application 2. Verification 3. Issuance",
        "services.work.case_study": "Secured permits for 20 employees in two weeks.",
        "services.residence.title": "Residence Permits",
        "services.residence.description": "Support for long-term stays in Ethiopia.",
        "services.residence.overview": "Long-term residence permits for investors and families.",
        "services.residence.process": "1. Documentation 2. Submission 3. Approval",
        "services.residence.case_study": "Helped a family secure residence permits in one month.",
        "services.license.title": "Business License Processing",
        "services.license.description": "Navigate licensing requirements with ease.",
        "services.license.overview": "Effortless business license processing in Ethiopia.",
        "services.license.process": "1. Consultation 2. Application 3. Approval",
        "services.license.case_study": "Secured a license for a retail business in three weeks.",
        "services.legal.title": "Legal Consultancy",
        "services.legal.description": "Expert advice on business compliance.",
        "services.legal.overview": "Legal support for business compliance in Ethiopia.",
        "services.legal.process": "1. Assessment 2. Advisory 3. Compliance",
        "services.legal.case_study": "Resolved a compliance issue for a Chinese firm.",
        "services.financial.title": "Financial Consultancy",
        "services.financial.description": "Optimize your investments with expert planning.",
        "services.financial.overview": "Financial planning and investment optimization for investors.",
        "services.financial.process": "1. Analysis 2. Planning 3. Execution",
        "services.financial.case_study": "Improved ROI for a client’s investment portfolio.",
        "services.overview": "Overview",
        "services.process": "Process",
        "services.case_study": "Case Study",
        "services.cta": "Start Now",
        "services.link": "Learn More",
        "why.title": "Why Unify Consultancy",
        "why.description": "With over 500 visas processed and 300 licenses secured, we’re trusted by Chinese investors.",
        "why.testimonial": "“Unify Consultancy helped me secure a business license in just weeks!” – Sample Client",
        "why.hero.title": "Why Unify Consultancy is Your Best Choice for Ethiopia",
        "why.hero.subtitle": "Fast, cost-effective, and expert solutions for Chinese investors.",
        "why.strengths.speed.title": "Speed",
        "why.strengths.speed.description": "We deliver visas and licenses in weeks, not months.",
        "why.strengths.cost.title": "Cost-Effectiveness",
        "why.strengths.cost.description": "Transparent pricing for premium services.",
        "why.strengths.expertise.title": "Expertise",
        "why.strengths.expertise.description": "Specialists in visa, legal, and financial consultancy.",
        "why.strengths.network.title": "Wide Network",
        "why.strengths.network.description": "Connections with Ethiopian immigration and government.",
        "why.testimonial1": "“Unify Consultancy’s speed made starting my business effortless!” – Sample Client",
        "why.testimonial2": "“Their network saved us weeks of delays.” – Sample Client",
        "why.cta.button": "Start Your Journey with Us",
        "cta.title": "Request a Free Consultation",
        "cta.button": "Get Started",
        "about.hero.title": "Your Trusted Partner for Business Success in Ethiopia",
        "about.hero.subtitle": "Unify Consultancy delivers fast, expert solutions for Chinese investors.",
        "about.hero.cta": "Contact Our Team",
        "about.mission.title": "Our Mission",
        "about.mission.description": "At Unify Consultancy, our mission is to empower Chinese nationals to succeed in Ethiopia’s vibrant business environment.",
        "about.expertise.title": "Our Expertise",
        "about.expertise.description": "With over 500 visas processed and 300 licenses secured, we’re a trusted leader for Chinese investors in Ethiopia.",
        "about.team.title": "Our Team",
        "about.team.description": "Our team of experts in visa processing, legal consultancy, and financial planning is passionate about helping Chinese investors thrive. [Bios to be added later.]",
        "about.certifications.title": "Certifications",
        "about.certifications.description": "Unify Consultancy maintains affiliations with leading industry organizations, ensuring quality in all services. [Details to be added later.]",
        "resources.hero.title": "Resources to Start Your Business in Ethiopia",
        "resources.hero.subtitle": "Explore expert guides and insights for Chinese investors.",
        "resources.tips.title": "Top 5 Tips for Chinese Nationals to Secure an Investor Visa",
        "resources.tips.description": "Learn the key steps to a successful visa application.",
        "resources.tips.link": "Read More",
        "resources.checklist.title": "Ethiopia Investor Visa Checklist",
        "resources.checklist.description": "Download our free checklist to prepare your application.",
        "resources.checklist.link": "Download",
        "resources.newsletter.title": "Stay Updated",
        "resources.newsletter.description": "Stay updated on Ethiopia’s immigration policies and business opportunities.",
        "resources.newsletter.placeholder": "Your Email",
        "resources.newsletter.button": "Subscribe",
        "contact.hero.title": "Get in Touch with Unify Consultancy",
        "contact.hero.subtitle": "Start your business journey in Ethiopia today.",
        "contact.form.title": "Contact Us",
        "contact.form.subtitle": "Have questions about visas, licenses, or starting a business in Ethiopia? Fill out the form below.",
        "contact.form.name": "Name",
        "contact.form.email": "Email",
        "contact.form.phone": "Phone",
        "contact.form.service": "Service Type",
        "contact.form.service.visa": "Visa Processing",
        "contact.form.service.license": "Business License Processing",
        "contact.form.service.legal": "Legal Consultancy",
        "contact.form.service.financial": "Financial Consultancy",
        "contact.form.message": "Message",
        "contact.form.submit": "Submit",
        "contact.booking.title": "Book a Free Consultation",
        "contact.booking.subtitle": "Schedule a free consultation with our experts.",
        "contact.details.title": "Contact Information",
        "contact.details.info": "Phone: [Your Phone Number]<br>Email: [Your Email]<br>Address: [Your Address, e.g., Addis Ababa, Ethiopia]",
        "portal.hero.title": "Client Portal",
        "portal.hero.subtitle": "Track the status of your applications with Unify Consultancy.",
        "portal.login.title": "Login to Your Portal",
        "portal.login.subtitle": "Client Portal is under development. Please login with your credentials.",
        "portal.login.username": "Username",
        "portal.login.password": "Password",
        "portal.login.button": "Login",
        "portal.login.support": "Or <a href='contact.html'>contact us</a> for support.",
        "nav.home": "Home",
        "nav.about": "About Us",
        "nav.services": "Services",
        "nav.why": "Why Choose Us",
        "nav.resources": "Resources",
        "nav.contact": "Contact Us",
        "nav.portal": "Client Portal",
        "footer.copyright": "© 2025 Unify Consultancy. All rights reserved.",
        "footer.contact": "Contact Us"
    },
    ar: {
        "hero.title": "أطلق عملك في إثيوبيا مع Unify Consultancy",
        "hero.subtitle": "نقدم حلولاً سريعة وفعّالة من حيث التكلفة للمستثمرين الصينيين، من التأشيرات والتراخيص إلى الاستشارات القانونية والمالية.",
        "hero.cta": "حجز استشارة",
        "services.title": "خدماتنا",
        "services.economic.title": "استشارات التنمية الاقتصادية",
        "services.economic.description": "استراتيجيات متخصصة لدخول السوق في إثيوبيا.",
        "services.economic.overview": "تقدم Unify Consultancy استراتيجيات متخصصة لدخول السوق في إثيوبيا، مما يساعد المواطنين الصينيين على تحديد فرص النمو.",
        "services.economic.process": "1. استشارة 2. تحليل السوق 3. تنفيذ الاستراتيجية",
        "services.economic.case_study": "حددت شركة صينية فرص النمو بمساعدتنا.",
        "services.business.title": "استشارات الأعمال والاستثمار",
        "services.business.description": "دعم لإنشاء الأعمال في أي صناعة.",
        "services.business.overview": "نرشدك خلال إنشاء الأعمال في إثيوبيا عبر أي صناعة.",
        "services.business.process": "1. التخطيط 2. التنفيذ 3. النمو",
        "services.business.case_study": "أطلق عميل بنجاح وحدة تصنيع في أديس أبابا.",
        "services.visa.title": "معالجة التأشيرات",
        "services.visa.description": "تأمين تأشيرات المستثمرين بسرعة من خلال عمليتنا.",
        "services.visa.overview": "معالجة تأشيرات سريعة للمستثمرين الصينيين.",
        "services.visa.process": "1. جمع الوثائق 2. تقديم الطلب 3. الموافقة",
        "services.visa.case_study": "تمت معالجة أكثر من 50 تأشيرة في شهر واحد لمجموعة شركات.",
        "services.work.title": "تصاريح العمل",
        "services.work.description": "تصاريح مبسطة للموظفين الصينيين.",
        "services.work.overview": "تصاريح عمل خالية من المتاعب لفريقك في إثيوبيا.",
        "services.work.process": "1. الطلب 2. التحقق 3. الإصدار",
        "services.work.case_study": "تم تأمين تصاريح لـ 20 موظفًا في أسبوعين.",
        "services.residence.title": "تصاريح الإقامة",
        "services.residence.description": "دعم للإقامة طويلة الأمد في إثيوبيا.",
        "services.residence.overview": "تصاريح إقامة طويلة الأمد للمستثمرين والعائلات.",
        "services.residence.process": "1. الوثائق 2. التقديم 3. الموافقة",
        "services.residence.case_study": "ساعدنا عائلة في تأمين تصاريح الإقامة في شهر واحد.",
        "services.license.title": "معالجة تراخيص الأعمال",
        "services.license.description": "التعامل مع متطلبات الترخيص بسهولة.",
        "services.license.overview": "معالجة تراخيص الأعمال بسهولة في إثيوبيا.",
        "services.license.process": "1. الاستشارة 2. الطلب 3. الموافقة",
        "services.license.case_study": "تم تأمين ترخيص لأعمال بيع بالتجزئة في ثلاثة أسابيع.",
        "services.legal.title": "الاستشارات القانونية",
        "services.legal.description": "نصائح متخصصة حول الامتثال التجاري.",
        "services.legal.overview": "دعم قانوني للامتثال التجاري في إثيوبيا.",
        "services.legal.process": "1. التقييم 2. الاستشارة 3. الامتثال",
        "services.legal.case_study": "تم حل مشكلة امتثال لشركة صينية.",
        "services.financial.title": "الاستشارات المالية",
        "services.financial.description": "تحسين استثماراتك مع التخطيط المتخصص.",
        "services.financial.overview": "التخطيط المالي وتحسين الاستثمارات للمستثمرين.",
        "services.financial.process": "1. التحليل 2. التخطيط 3. التنفيذ",
        "services.financial.case_study": "تحسين العائد على الاستثمار لمحفظة استثمارية لعميل.",
        "services.overview": "نظرة عامة",
        "services.process": "العملية",
        "services.case_study": "دراسة حالة",
        "services.cta": "ابدأ الآن",
        "services.link": "تعرف على المزيد",
        "why.title": "لماذا Unify Consultancy",
        "why.description": "مع أكثر من 500 تأشيرة تمت معالجتها و300 ترخيص تم تأمينها، نحن موثوقون من قبل المستثمرين الصينيين.",
        "why.testimonial": "“ساعدتني Unify Consultancy في تأمين ترخيص أعمال في غضون أسابيع فقط!” – عميل عينة",
        "why.hero.title": "لماذا Unify Consultancy هو خيارك الأفضل لإثيوبيا",
        "why.hero.subtitle": "حلول سريعة وفعّالة من حيث التكلفة ومتخصصة للمستثمرين الصينيين.",
        "why.strengths.speed.title": "السرعة",
        "why.strengths.speed.description": "نقدم التأشيرات والتراخيص في أسابيع، وليس أشهر.",
        "why.strengths.cost.title": "الفعالية من حيث التكلفة",
        "why.strengths.cost.description": "تسعير شفاف لخدمات متميزة.",
        "why.strengths.expertise.title": "الخبرة",
        "why.strengths.expertise.description": "متخصصون في التأشيرات والاستشارات القانونية والمالية.",
        "why.strengths.network.title": "شبكة واسعة",
        "why.strengths.network.description": "علاقات مع الهجرة والحكومة الإثيوبية.",
        "why.testimonial1": "“سرعة Unify Consultancy جعلت بدء عملي سهلاً!” – عميل عينة",
        "why.testimonial2": "“شبكتهم وفرت لنا أسابيع من التأخير.” – عميل عينة",
        "why.cta.button": "ابدأ رحلتك معنا",
        "cta.title": "طلب استشارة مجانية",
        "cta.button": "ابدأ الآن",
        "about.hero.title": "شريكك الموثوق لنجاح الأعمال في إثيوبيا",
        "about.hero.subtitle": "تقدم Unify Consultancy حلولاً سريعة ومتخصصة للمستثمرين الصينيين.",
        "about.hero.cta": "اتصل بفريقنا",
        "about.mission.title": "مهمتنا",
        "about.mission.description": "في Unify Consultancy، مهمتنا هي تمكين المواطنين الصينيين من النجاح في بيئة الأعمال النابضة بالحياة في إثيوبيا.",
        "about.expertise.title": "خبرتنا",
        "about.expertise.description": "مع أكثر من 500 تأشيرة تمت معالجتها و300 ترخيص تم تأمينها، نحن قادة موثوقون للمستثمرين الصينيين في إثيوبيا.",
        "about.team.title": "فريقنا",
        "about.team.description": "فريقنا من الخبراء في معالجة التأشيرات والاستشارات القانونية والتخطيط المالي متحمس لمساعدة المستثمرين الصينيين على الازدهار. [السير الذاتية ستُضاف لاحقًا.]",
        "about.certifications.title": "الشهادات",
        "about.certifications.description": "تحافظ Unify Consultancy على علاقات مع منظمات صناعية رائدة، مما يضمن الجودة في جميع خدماتنا. [التفاصيل ستُضاف لاحقًا.]",
        "resources.hero.title": "موارد لبدء عملك في إثيوبيا",
        "resources.hero.subtitle": "استكشف أدلة وتوصيات متخصصة للمستثمرين الصينيين.",
        "resources.tips.title": "أفضل 5 نصائح للمواطنين الصينيين لتأمين تأشيرة مستثمر",
        "resources.tips.description": "تعرف على الخطوات الأساسية لتقديم طلب تأشيرة ناجح.",
        "resources.tips.link": "اقرأ المزيد",
        "resources.checklist.title": "قائمة مراجعة تأشيرة المستثمر في إثيوبيا",
        "resources.checklist.description": "قم بتنزيل قائمة المراجعة المجانية لتحضير طلبك.",
        "resources.checklist.link": "تنزيل",
        "resources.newsletter.title": "ابقَ على اطلاع",
        "resources.newsletter.description": "ابقَ على اطلاع بسياسات الهجرة والفرص التجارية في إثيوبيا.",
        "resources.newsletter.placeholder": "بريدك الإلكتروني",
        "resources.newsletter.button": "اشترك",
        "contact.hero.title": "تواصل مع Unify Consultancy",
        "contact.hero.subtitle": "ابدأ رحلتك التجارية في إثيوبيا اليوم.",
        "contact.form.title": "تواصل معنا",
        "contact.form.subtitle": "هل لديك أسئلة حول التأشيرات أو التراخيص أو بدء عمل تجاري في إثيوبيا؟ املأ النموذج أدناه.",
        "contact.form.name": "الاسم",
        "contact.form.email": "البريد الإلكتروني",
        "contact.form.phone": "الهاتف",
        "contact.form.service": "نوع الخدمة",
        "contact.form.service.visa": "معالجة التأشيرات",
        "contact.form.service.license": "معالجة تراخيص الأعمال",
        "contact.form.service.legal": "الاستشارات القانونية",
        "contact.form.service.financial": "الاستشارات المالية",
        "contact.form.message": "الرسالة",
        "contact.form.submit": "إرسال",
        "contact.booking.title": "احجز استشارة مجانية",
        "contact.booking.subtitle": "حدد موعدًا لاستشارة مجانية مع خبرائنا.",
        "contact.details.title": "معلومات الاتصال",
        "contact.details.info": "الهاتف: [رقم هاتفك]<br>البريد الإلكتروني: [بريدك الإلكتروني]<br>العنوان: [عنوانك، على سبيل المثال، أديس أبابا، إثيوبيا]",
        "portal.hero.title": "بوابة العميل",
        "portal.hero.subtitle": "تتبع حالة طلباتك مع Unify Consultancy.",
        "portal.login.title": "تسجيل الدخول إلى بوابتك",
        "portal.login.subtitle": "بوابة العميل قيد التطوير. يرجى تسجيل الدخول باستخدام بياناتك.",
        "portal.login.username": "اسم المستخدم",
        "portal.login.password": "كلمة المرور",
        "portal.login.button": "تسجيل الدخول",
        "portal.login.support": "أو <a href='contact.html'>تواصل معنا</a> للحصول على الدعم.",
        "nav.home": "الرئيسية",
        "nav.about": "معلومات عنا",
        "nav.services": "الخدمات",
        "nav.why": "لماذا تختارنا",
        "nav.resources": "الموارد",
        "nav.contact": "اتصل بنا",
        "nav.portal": "بوابة العميل",
        "footer.copyright": "© 2025 Unify Consultancy. جميع الحقوق محفوظة.",
        "footer.contact": "اتصل بنا"
    }
};

const elements = document.querySelectorAll('[data-translate]');
const placeholderElements = document.querySelectorAll('[data-translate-placeholder]');
const savedLang = localStorage.getItem('language') || 'zh';
document.body.setAttribute('lang', savedLang);
languageSelect.value = savedLang;

languageSelect.addEventListener('change', (e) => {
    const lang = e.target.value;
    document.body.setAttribute('lang', lang);
    localStorage.setItem('language', lang);
    updateLanguage(lang);
});

function updateLanguage(lang) {
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (translations[lang][key]) {
            element.innerHTML = translations[lang][key];
            element.setAttribute('lang-active', '');
        } else {
            element.removeAttribute('lang-active');
        }
    });

    placeholderElements.forEach(element => {
        const key = element.getAttribute('data-translate-placeholder');
        if (translations[lang][key]) {
            element.setAttribute('placeholder', translations[lang][key]);
            element.setAttribute('lang-active', '');
        } else {
            element.removeAttribute('lang-active');
        }
    });

    const pageTitles = {
        'index.html': { zh: 'Unify Consultancy | 咨询统', en: 'Unify Consultancy', ar: 'Unify Consultancy | استشارات موحدة' },
        'about.html': { zh: 'About Us | 关于我们', en: 'About Us', ar: 'معلومات عنا' },
        'services.html': { zh: 'Services | 服务', en: 'Services', ar: 'الخدمات' },
        'why-choose-us.html': { zh: 'Why Choose Us | 选择我们', en: 'Why Choose Us', ar: 'لماذا تختارنا' },
        'resources.html': { zh: 'Resources | 资源', en: 'Resources', ar: 'الموارد' },
        'contact.html': { zh: 'Contact Us | 联系我们', en: 'Contact Us', ar: 'اتصل بنا' },
        'client-portal.html': { zh: 'Client Portal | 客户门户', en: 'Client Portal', ar: 'بوابة العميل' }
    };

    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    document.title = pageTitles[currentPage][lang] || 'Unify Consultancy';
}

updateLanguage(savedLang);